#!/usr/bin/env bash

current=$(hyprctl activeworkspace -j | jq -r '.id')

hyprctl clients -j |
jq -r '.[] | select(.workspace.id == -99) | .address' |
while read addr; do
    hyprctl dispatch movetoworkspace "$current,address:$addr"
done
