[urgency_low]
background = "#FFFFFFAA"
foreground = "#111111"
frame_color = "#FFFFFFB3"
icon = "/home/bug/.local/share/icons/Wallbash-Icon/hyprdots.svg"
timeout = 5

[urgency_normal]
background = "#FFFFFFAA"
foreground = "#111111"
frame_color = "#FFFFFFB3"
icon = "/home/bug/.local/share/icons/Wallbash-Icon/hyprdots.svg"
timeout = 7

[urgency_critical]
background = "#FFEBEBAA"
foreground = "#111111"
frame_color = "#FF3B30CC"
icon = "/home/bug/.local/share/icons/Wallbash-Icon/critical.svg"
timeout = 0
